---
## retrieve ghe versions installed (primary & replica)
- name: read current ghe version
  command: ghe-version
  register: ghe_version
  changed_when: ghe_version.rc == 0
  notify:
    - save ghe version info
    - parse ghe version info
