---
## retrieve ghe versions installed (primary & replica)
- name: read current ghe version
  command: ghe-version
  register: gh_version
  changed_when: true
  notify:
    - save ghe version info
    - parse ghe version info
    - compare ghe versions
