---
## check if we donloaded the pkg|hpkg file manually
## or if automatic update checks are enabled
## see: https://git.io/fAUUU
- name: check if upgrade package is available
  find:
    paths:
      - '~'
      - '/var/lib/ghe-updates'
    patterns:
      - '*.pkg'
      - '*.hpkg'
  register: pkg_update_files
  changed_when:
    - pkg_update_files.matched != 0
  ignore_errors: yes
  notify:
    - save pkg filepath from automatic/manual download
    - parse pkg file info
    - currently on the latest release
    - is upgrade to new feature version
    - compare download pkg versions

## run `ghe-update-check` to download the upgrade package
## only executed if update pkg|hpkg wasn't downloaded automaticall/manually
- name: download pkg
  command: ghe-update-check
  register: pkg_download_files
  changed_when:
    - pkg_download_files.rc == 0
  notify:
    - save pkg filepath from download
    - parse pkg file info
    - currently on the latest release
    - is upgrade to new feature version
    - compare download pkg versions
  when: pkg_update_files.matched == 0
