---
- name: get ghe version (primary)
  hosts: github_primary
  gather_facts: false
  roles:
    - ghe-version

- name: get ghe version (replica)
  hosts: github_replica
  gather_facts: false
  roles:
    - ghe-version

- name: check/download update package (primary)
  hosts: github_primary
  gather_facts: false
  roles:
    - ghe-update-download

- name: check/download update package (replica)
  hosts: github_replica
  gather_facts: false
  roles:
    - ghe-update-download

- name: update backup-utils
  hosts: github_backup
  gather_facts: false
  roles:
    - backup-update

- name: set maintenance mode
  hosts: github_primary
  gather_facts: false
  roles:
    - role: ghe-maintenance-set
      vars:
        ## sleep X seconds
        ## defaults to 600 seconds (10 mins) if not set
        sleep: 5
      when: not hostvars['github_primary'].is_hotpatch

- name: stop replication
  hosts: github_replica
  gather_facts: false
  roles:
    - role: ghe-repl-stop
      when: not hostvars['github_primary'].is_hotpatch

- name: create a backup
  hosts: github_backup
  gather_facts: false
  roles:
    - backup-run

- name: update ghe (primary)
  hosts: github_primary
  gather_facts: false
  roles: []

- name: update ghe (replica)
  hosts: github_replica
  gather_facts: false
  roles: []

- name: start replication
  hosts: github_replica
  gather_facts: false
  roles:
    - role: ghe-repl-start
      when: not hostvars['github_primary'].is_hotpatch

- name: unset maintenance mode
  hosts: github_primary
  gather_facts: false
  roles:
    - role: ghe-maintenance-unset
      when: not hostvars['github_primary'].is_hotpatch
