---
- hosts: github_primary
  gather_facts: false

  roles:
    - ghe-version

- hosts: github_replica
  gather_facts: false

  roles:
    - ghe-version

- hosts: github_primary
  gather_facts: false

  roles:
    - ghe-update

- hosts: github_replica
  gather_facts: false

  roles:
    - ghe-update
