---
- hosts: github_primary
  gather_facts: false
  roles:
    - ghe-version

- hosts: github_replica
  gather_facts: false
  roles:
    - ghe-version

- hosts: github_primary
  gather_facts: false
  roles:
    - ghe-update-download

- hosts: github_replica
  gather_facts: false
  roles:
    - ghe-update-download

- hosts: github_backup
  gather_facts: false
  roles:
    - backup-update
