---
## upgrade ghe
## this disconnects SSH for pkg upgrades,
## so we need to ignore any error and
## wait for it to be available again
- name: upgrade to v{{ hostvars[inventory_hostname].pkg_full }}
  command: "ghe-upgrade --yes {{ hostvars[inventory_hostname].pkg_filepath }}"
  ignore_errors: yes
  register: gh_upgraded
  changed_when: true
  notify:
    - hpkg reboot required

## reset the above encountered errors
## so the play does not fail
## see: https://docs.ansible.com/ansible/user_guide/playbooks_error_handling.html#resetting-unreachable-hosts
- meta: clear_host_errors

## wait for ghe replica to be available again
- name: wait for SSH port to open again
  ## see: http://docs.ansible.com/ansible/latest/modules/wait_for_module.html
  wait_for:
    host: "{{ hostvars[inventory_hostname].ansible_host }}"
    port: "{{ hostvars[inventory_hostname].ansible_port }}"
    ## retry every 10 seconds
    delay: 10
    ## timeout after 5 minutes
    timeout: 300
    ## wait for an open connection
    state: started
