---
- name: get current backup utils version
  command: "cat {{ hostvars['backup']['home_dir'] }}/share/github-backup-utils/version"
  register: backup_utils_version_before
  changed_when: false

## auto update backup-utils (to keep in line with ghe)
## see: https://git.io/fAUUJ
- name: update backup utils
  git:
    repo: https://github.com/github/backup-utils.git
    dest: "{{ hostvars['backup']['home_dir'] }}"
    version: stable
    update: yes
    force: yes
  register: backup_utils
  changed_when: backup_utils.after != backup_utils.before

- name: get new backup utils version
  command: "cat {{ hostvars['backup']['home_dir'] }}/share/github-backup-utils/version"
  register: backup_utils_version_after
  changed_when: false

- name: backup utils version
  set_fact:
    messages: "{{ messages }} + ['[INFO]: upgraded backup utils from {{ backup_utils_version_before.stdout }} to {{ backup_utils_version_after.stdout }}']"
  when:
    - backup_utils_version_before is defined
    - backup_utils_version_after is defined
