---
- name: save ghe version info
  # parse the ghe version into https://semver.org format
  #   - ghe_version_full    2.15.3
  #   - ghe_version_major   2
  #   - ghe_version_minor   15
  #   - ghe_version_patch   3
  set_fact:
    ghe_version_full="{{ ghe_version.stdout | regex_search('([0-9]+\.[0-9]+\.[0-9]+)') }}"
    ghe_version_major="{{ ghe_version.stdout | regex_search(version_regex,'\\1') | first }}"
    ghe_version_minor="{{ ghe_version.stdout | regex_search(version_regex,'\\2') | first }}"
    ghe_version_patch="{{ ghe_version.stdout | regex_search(version_regex,'\\3') | first }}"
  vars:
    version_regex: '([0-9]+)\.([0-9]+)\.([0-9]+)'

- name: parse ghe version info
  debug:
    msg:
      - ghe_version_full: '{{ hostvars[inventory_hostname].ghe_version_full }}'
      - ghe_version_major: '{{ hostvars[inventory_hostname].ghe_version_major }}'
      - ghe_version_minor: '{{ hostvars[inventory_hostname].ghe_version_minor }}'
      - ghe_version_patch: '{{ hostvars[inventory_hostname].ghe_version_patch }}'
    verbosity: 1

- name: compare ghe versions
  fail: msg="[ABORT] Primary (v{{ hostvars['github_primary'].ghe_version_full }}) Replica (v{{ hostvars['github_replica'].ghe_version_full }}) versions must be identical"
  when:
    - hostvars['github_replica'].ghe_version_full is defined
    - hostvars['github_primary'].ghe_version_full != hostvars['github_replica'].ghe_version_full
