---
- name: save ghe version info
  # parse the ghe version into https://semver.org format
  #   - version_full    2.15.3
  #   - version_major   2
  #   - version_minor   15
  #   - version_patch   3
  set_fact:
    version_full="{{ gh_version.stdout | regex_search('([0-9]+\.[0-9]+\.[0-9]+)') }}"
    version_major="{{ gh_version.stdout | regex_search(version_regex,'\\1') | first }}"
    version_minor="{{ gh_version.stdout | regex_search(version_regex,'\\2') | first }}"
    version_patch="{{ gh_version.stdout | regex_search(version_regex,'\\3') | first }}"
  vars:
    version_regex: '([0-9]+)\.([0-9]+)\.([0-9]+)'

- name: parse ghe version info
  debug:
    msg:
      - version_full: '{{ hostvars[inventory_hostname].version_full }}'
      - version_major: '{{ hostvars[inventory_hostname].version_major }}'
      - version_minor: '{{ hostvars[inventory_hostname].version_minor }}'
      - version_patch: '{{ hostvars[inventory_hostname].version_patch }}'
    verbosity: 1

- name: compare ghe versions
  fail:
    msg: "[ABORT] primary v{{ hostvars['primary'].version_full }} !== replica v{{ hostvars['replica'].version_full }}"
  when:
    - hostvars['primary'].version_full is defined
    - hostvars['replica'].version_full is defined
    - hostvars['primary'].version_full != hostvars['replica'].version_full
